@extends('layouts.app')
@section('title', 'Premium Real Estate in Nigeria')
@section('content')
@include('public.home._hero')
@include('public.home._search')
@include('public.home._featured', ['featuredProperties' => $featuredProperties])
@include('public.home._property-categories')
@include('public.home._stats', ['stats' => $stats])
@include('public.home._why-us')
@include('public.home._home-sections')
@include('public.home._how-it-works')
@include('public.home._team', ['featuredTeam' => $featuredTeam])
@include('public.home._testimonials', ['testimonials' => $testimonials])
@include('public.home._blog', ['latestPosts' => $latestPosts])
@include('public.home._newsletter')
@include('public.home._partners', ['partners' => $partners, 'awards' => $awards])
@endsection
